version: "3.9"

services:
  client:
    build:
      context: ./budget-manager-client
      dockerfile: Dockerfile.prod
    container_name: buildbeam-client
    ports:
      - "3000:3000"   # Expose to host
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - buildbeam-network

networks:
  buildbeam-network:
    driver: bridge
